- .github/workflows/workflow_path_to_live.yml
- terraform/envs/devl/idam-testing/.terraform.lock.hcl
- terraform/envs/devl/idam-testing/main.tf
Fixes the path to live workflow looking for a non existent artifact
Fixes #
> Fix artifact issue

- terraform/envs/devl/idam-testing/main.tf
- terraform/envs/devl/idam-testing/variables.tf
- terraform/envs/devl/idam-testing/versions.tf
- terraform/modules/application-registrationV1/.terraform.lock.hcl
- terraform/modules/application-registrationV1/main.tf
- terraform/modules/application-registrationV1/outputs.tf
- terraform/modules/application-registrationV1/variables.tf
Testing app reg module
Fixes #
> Testing appreg

- terraform/envs/nle/modern-workplace/data.tf
- terraform/envs/nle/modern-workplace/main.tf
- terraform/envs/nle/modern-workplace/state.config
- terraform/envs/nle/modern-workplace/variables.tf
- terraform/envs/nle/modern-workplace/versions.tf
Create NLE App Registration for Genesys work. Part of IDAM-2828
> Initial draft of NLE app for Genesys

- terraform/envs/live/data-engineering/data.tf
- terraform/envs/live/data-engineering/main.tf
- terraform/envs/live/data-engineering/state.config
- terraform/envs/live/data-engineering/variables.tf
- terraform/envs/live/data-engineering/versions.tf
Preparing App Reg for IDAM-2726
> Idam 2726 app reg

- terraform/envs/devl/file-and-data-services/variables.tf
- terraform/envs/live/diso/data.tf
- terraform/envs/live/diso/main.tf
- terraform/envs/live/diso/state.config
- terraform/envs/live/diso/variables.tf
- terraform/envs/live/diso/versions.tf
> add diso files

- terraform/envs/live/diso/state.config
Points diso customer files to its own state file
Fixes #
> Update state file

- terraform/envs/live/diso/variables.tf
Change app name from TeamsRoutingApp to DISO-Hosted-Voice-Teams-Routing
Fixes #
> Update app name

- .pre-commit-config.yaml
- terraform/envs/devl/idam-testing/.terraform.lock.hcl
- terraform/envs/devl/idam-testing/variables.tf
Updates pre commit config
Fixes #
> Pre commit fix

- terraform/modules/application-registrationV1.1.0/main.tf
- terraform/modules/application-registrationV1.1.0/outputs.tf
- terraform/modules/application-registrationV1.1.0/variables.tf
Fixes not being allowed to pass 0 permissions into the app reg
Fixes #
> fix app reg

- terraform/envs/devl/eucs-vds/variables.tf
- terraform/envs/live/eucs-vds/variables.tf
Add housekeeping app reg's in live and devl
Fixes #
> add app regs

- .github/workflows/workflow_path_to_live.yml
**Title:**  
Remove manual approval stage
This removes the manual approval stage from the path to live workflow. This is because I feel like this adds an unnecessary stage to the workflow, as the code / change will already have been approved in the PR by the correct level of engineer. Thus we do not need to approve again on the main branch.
**Fixes:** [Jira-3608](https://dsdmoj.atlassian.net/browse/IDAM-3608)
---
> remove manual approval

- terraform/envs/devl/diso/data.tf
- terraform/envs/devl/diso/main.tf
- terraform/envs/devl/diso/state.config
- terraform/envs/devl/diso/variables.tf
- terraform/envs/devl/diso/versions.tf
Title: 
Create a Graph API app reg
Description: 
This creates a basic App reg and SP which will allow use to give the diso team access to graph api scopes/permissions
Fixes: [Jira-1811](https://dsdmoj.atlassian.net/browse/IDAM-1811)
---
> create app reg

- terraform/envs/devl/m365/data.tf
- terraform/envs/devl/m365/main.tf
- terraform/envs/devl/m365/state.config
- terraform/envs/devl/m365/variables.tf
- terraform/envs/devl/m365/versions.tf
Title: 
Create a Graph API app reg
Description: 
This creates a basic App reg and SP which will allow use to give the M365 teams access to graph api scopes/permissions
Fixes: [Jira-1811](https://dsdmoj.atlassian.net/browse/IDAM-1811)
---
> create m365 app reg's

- terraform-template/data.tf
- terraform-template/main.tf
- terraform-template/state.config
- terraform-template/variables.tf
- terraform-template/versions.tf
**Title:**  
Create Terraform Template
Create a `Terraform Template` folder. This is so that other teams/engineers can clone our repo and have a default config to copy for app reg's
**Fixes:** [Jira-2767](https://dsdmoj.atlassian.net/browse/IDAM-2767)
---
> create terraform template

- terraform/envs/live/ims-cfhands/data.tf
- terraform/envs/live/ims-cfhands/main.tf
- terraform/envs/live/ims-cfhands/state.config
- terraform/envs/live/ims-cfhands/variables.tf
- terraform/envs/live/ims-cfhands/versions.tf
**Title:**  
_Create SSO app for Sphere Incident Management System._
_Create a new SSO app registration
[Jira-IDAM-2788] https://dsdmoj.atlassian.net/browse/IDAM-2788_
---
> create sso app for IMS

- terraform/envs/nleexternal/laa/data.tf
- terraform/envs/nleexternal/laa/main.tf
- terraform/envs/nleexternal/laa/state.config
- terraform/envs/nleexternal/laa/variables.tf
- terraform/envs/nleexternal/laa/versions.tf
**Title:**  
Adds baseline configuration for the `LASSIE` LAA Application
Adds the baseline configuration for the `LASSIE` LAA Application with the following Application Permission. These will be cut down soon but replicating DEVL for now.
> Before moving to PROD these will need justifying ahead of a Change Request.
* `CustomAuthenticationExtension.Receive.Payload`
* `User.Invite.All`
* `Directory.Read.All`
* `User.Read.All`
* `GroupMember.ReadWrite.All`
* `AuditLog.Read.All`
* `Application.Read.All`
**Fixes:** [Jira-2974](https://dsdmoj.atlassian.net/browse/IDAM-2974)
---
> Add baseline `LASSIE` LAA Application

- terraform/envs/nleexternal/laa/main.tf
- terraform/envs/nleexternal/laa/variables.tf
- terraform/modules/application-registrationV1.2.1/main.tf
- terraform/modules/application-registrationV1.2.1/outputs.tf
- terraform/modules/application-registrationV1.2.1/variables.tf
**Title:**  
Add Application Contacts
* Update application-registration module to include `application_contacts` allowing us to have a list of users to contact for the application in the future.
* Update `LASSIE` app to use these properties
**Fixes:** [Jira-2974](https://dsdmoj.atlassian.net/browse/IDAM-2974)
> Add Application Contacts

- terraform/envs/nleexternal/laa/variables.tf
**Title:**  
Enable Claims for LAA Apps in SILAS MVP
Enable the LAA Apps that are part of SILAS MVP to accept claims
**Fixes:** N/A
---
> Enable Claims for LAA Apps in SILAS MVP

- terraform/envs/devl/eucs-vds/variables.tf
**Title:**  
Create VDS Devl App Regs
New App Regs required for use in AZDO Terraform pipelines.
Graph permissions are required as VDS need to create Entra Groups, and add users to them, which will then be used as access groups to AVD hostpools for said users.
Ticket ref - https://dsdmoj.atlassian.net/browse/EUCSVDS-1512
---
> add VDS devl app regs, for terraform use

- terraform/envs/nleexternal/laa/variables.tf
**Title:**  
Update `Submit a Crime Form` urls to uat
Update `Submit a Crime Form` urls to uat
---
> Update `Submit a Crime Form` urls to uat

- terraform/envs/prodexternal/laa/data.tf
- terraform/envs/prodexternal/laa/main.tf
- terraform/envs/prodexternal/laa/state.config
- terraform/envs/prodexternal/laa/variables.tf
- terraform/envs/prodexternal/laa/versions.tf
> DO NOT MERGE, AWAITING CHANGE REQUEST
**Title:**  
Adds LAA Applications to ProdExternal
Adds the following Applications
* PUI
* LASSIE
* laad-lassie-claim-enrichment-api
* Apply for Civil Legal Aid
* Apply for Criminal Legal Aid
* Manage a Provider''s Data
* Submit A Crime Form
**Fixes:** [Jira-3913](https://dsdmoj.atlassian.net/browse/IDAM-3913)
---
> Adds LAA Applications to ProdExternal

- terraform/envs/prodexternal/laa/variables.tf
**Title:**  
Remove `identifier_uris`
On an initial creation you cannot set `identifier_uris` as they are not valid.
---
> Remove identifier_uris

- terraform/envs/devl/justice-ai/data.tf
- terraform/envs/devl/justice-ai/main.tf
- terraform/envs/devl/justice-ai/state.config
- terraform/envs/devl/justice-ai/variables.tf
- terraform/envs/devl/justice-ai/versions.tf
**Title:**  
Replicate live justice ai config to devl
Replicate live justice ai config to devl
**Fixes:** [IDAM-2889](https://dsdmoj.atlassian.net/browse/IDAM-2889)
---
[IDAM-2889]: https://dsdmoj.atlassian.net/browse/IDAM-2889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Replicate live to dev

- terraform/envs/prodexternal/laa/variables.tf
**Title:**  
Update LAA application changes
---
> Update LAA application changes

- terraform/envs/prodexternal/laa/variables.tf
**Title:**  
Add SiLAS `identifier_uris`
---
> Add SiLAS `identifier_uris`

- scripts/pipeline/Get-Changes.ps1
- terraform/envs/devl/idam-internal/variables.tf
**Title:**  
Fix main
Adds in logic to compare main against the previous commit to get the changed files
**Fixes:** [IDAM-4098](https://dsdmoj.atlassian.net/browse/IDAM-4098)
---
[IDAM-4098]: https://dsdmoj.atlassian.net/browse/IDAM-4098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Idam 4098 fix main

- terraform/envs/nleexternal/laa/variables.tf
**Title:**  
Change PUI NLE redirects
**Fixes:** [Jira-xxxx](https://dsdmoj.atlassian.net/browse/IDAM-xxxx)
---
> Change redirects for PUI NLE

- terraform/envs/nleexternal/laa/variables.tf
**Title:**  
Change PUI identifier url in NLE
**Fixes:** [Jira-xxxx](https://dsdmoj.atlassian.net/browse/IDAM-xxxx)
---
> Change PUI identifier url in NLE

- terraform/envs/live/ims-cfhands/main.tf
- terraform/envs/live/ims-cfhands/variables.tf
- terraform/envs/nleexternal/laa/variables.tf
- terraform/modules/application-registrationV1.3.0/main.tf
- terraform/modules/application-registrationV1.3.0/outputs.tf
- terraform/modules/application-registrationV1.3.0/variables.tf
**Title:**  
Adding token claims and delegated permissions to sphera application 
Adding token claims and delegated permissions to sphera application 
https://dsdmoj.atlassian.net/browse/IDAM-2788
---
> Adding token claims to application

- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pull_request.yml
- terraform/envs/devl/idam-testing/variables.tf
Reverts ministryofjustice/staff-identity-idam-entra-infra#254
> Revert "Change workflow script"

- terraform/envs/live/idam-internal/data.tf
- terraform/envs/live/idam-internal/main.tf
- terraform/envs/nle/idam-internal/data.tf
- terraform/envs/nle/idam-internal/main.tf
**Title:**  
Adding kv to live and nle
Add's KV's to nle and live to store env vars
**Fixes:** [IDAM-4019](https://dsdmoj.atlassian.net/browse/IDAM-4019)
---
[IDAM-4019]: https://dsdmoj.atlassian.net/browse/IDAM-4019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adding kv to live and nle

- scripts/Get-EnvVars.ps1
- terraform/envs/devl/idam-internal/main.tf
- terraform/envs/devl/idam-internal/variables.tf
**Title:**  
Update access policy and script
Updates the internal keyvault access policy in DEVL.
Deploys script to access internal keyvaults to pull secrets
**Fixes:** [IDAM-4019](https://dsdmoj.atlassian.net/browse/IDAM-4019)
---
[IDAM-4019]: https://dsdmoj.atlassian.net/browse/IDAM-4019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update access policy and script

- terraform/envs/live/STG/variables.tf
**Title:**  
Added redirect URI to PTRG app
**Fixes:** IDAM-4423
---
> Added redirect URI to PTRG app

- terraform/envs/live/DEDSAI-DMET/state.config
- terraform/envs/live/DEDSAI-DMET/variables.tf
**Title:**  
_A clear and concise title for the PR._
**Fixes:** [Jira-xxxx](https://dsdmoj.atlassian.net/browse/IDAM-xxxx)
---
> APP-REG-MoJO-DEDSAI-DMET-MDS

- terraform/envs/devl/eucs-vds/variables.tf
**Title:**  
_New DEVL SP for VDS._
VDS will use this SP for automated creation of AVD images
**Fixes:** [Jira-1712]
---
> new devl SP for VDS

- terraform/envs/live/STG/variables.tf
**Title:**  
changing scope type to users can approve to this app
https://dsdmoj.atlassian.net/jira/software/c/projects/IDAM/boards/1553?assignee=712020%3A02cde213-8061-47e3-9e6c-fe778ed13608&selectedIssue=IDAM-4423
---
> changing scope type to users can approve to this app
